apiVersion: apps/v1
kind: Deployment
metadata:
  name: iapp-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: iapp
  template:
    metadata:
      labels:
        app: iapp
    spec:
      containers:
        - name: iapp
          image: kevinhc47/iapp_1-i:latest  
          ports:
            - containerPort: 5000 
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "mydatabase"
