apiVersion: v1
kind: Service
metadata:
  name: iapp-service
spec:
  selector:
    app: iapp
  ports:
    - name: iapp1
      protocol: TCP
      port: 80
      targetPort: 5000  # Puerto del contenedor iapp1
    - name: iapp2
      protocol: TCP
      port: 81
      targetPort: 5001  # Puerto del contenedor iapp2
